"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.configureBuildFiles = exports.configureMainApplication = exports.AndroidConfigManager = exports.resolveModulePath = exports.detectModule = exports.PathResolver = void 0;
var path_resolver_1 = require("./path-resolver");
Object.defineProperty(exports, "PathResolver", { enumerable: true, get: function () { return path_resolver_1.PathResolver; } });
Object.defineProperty(exports, "detectModule", { enumerable: true, get: function () { return path_resolver_1.detectModule; } });
Object.defineProperty(exports, "resolveModulePath", { enumerable: true, get: function () { return path_resolver_1.resolveModulePath; } });
var android_config_1 = require("./android-config");
Object.defineProperty(exports, "AndroidConfigManager", { enumerable: true, get: function () { return android_config_1.AndroidConfigManager; } });
Object.defineProperty(exports, "configureMainApplication", { enumerable: true, get: function () { return android_config_1.configureMainApplication; } });
Object.defineProperty(exports, "configureBuildFiles", { enumerable: true, get: function () { return android_config_1.configureBuildFiles; } });
